parameters:
  csv_import_directory: '%kernel.project_dir%/%env(resolve:UPLOADS_PARENT)%/uploads/import'
  import_directory: '%kernel.project_dir%/%env(resolve:IMPORT_DIRECTORY)%'
  upload_directory: '%kernel.project_dir%/%env(resolve:UPLOADS_PARENT)%/uploads'
  upload_target_url: '/api/upload/'
  existing_uploads_url: '/catalogue/node/item/resources/'
  dump_existing_uploads_url: '/garbage/node/resources/'
  unfinished_uploads_url: '/api/upload/unfinished/'
  commit_upload_url: '/api/upload/commit'
  remove_upload_url: '/api/upload/remove'
  resource_url: '/catalogue/node/item/resource/'
  item_url: '/catalogue/node/item/'
  item_search_url: '/catalogue/search/items/'
  garbage_search_url: '/catalogue/search/garbage/'
  get_nodes_url: '/catalogue/nodes/'
  get_garbage_nodes_url: '/garbage/nodes/'
  get_node_url: '/catalogue/node/'
  get_garbage_node_url: '/garbage/node/'
  add_garbage_node_url: '/garbage/node/add'
  update_garbage_node_url: '/garbage/node/update'
  remove_garbage_node_url: '/garbage/node/remove'
  restore_garbage_node_url: '/garbage/node/restore'
  get_items_url: '/catalogue/node/items/'
  upload_url: '/upload'
  max_main_resources: 1
  max_additional_resources: 99
  placeholder_url: '/catalogue/resource/placeholder'
